name: GitHub Actions Practice - Lab 2

on:
  push:
    branches:
      - main

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Show files before checkout
        run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files after checkout
        run: ls -la

      - name: Show current directory
        run: pwd

      - name: Show Git status
        run: git status
