name: GitHub Actions Practice - Lab 4

on:
  workflow_dispatch:

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "This workflow was started manually!"

      - name: Show date
        run: date
